project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]

  sidebar:
    style: floating
    contents:
      - index.qmd
      - auto: "/*.ipynb"
      - section: Papers
        contents:
          - papers/01_Classics.qmd
          - papers/02_How.qmd
          - papers/03_Apps.qmd
          - papers/04_Hope.qmd
          - papers/05_Risks.qmd
          - papers/06_Patterns.qmd
          - papers/07_Methods.qmd
          - papers/08_Survey.qmd

      - section: Blogs
        contents:
          - blogs/01_top.qmd
          - blogs/02_chronicles.qmd
      - section: Tools
        contents:
          - codes/01_frameworks.qmd
          - codes/02_demos.qmd
    
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Latest"
        href: Hot.qmd
      
      - text: "Models"
        href: models.qmd
      - text: "Datasets"
        href: datasets.qmd
      
      - text: "Wadhwani AI"
        menu:
          - text: "About Us"
            icon: people-fill
            href: https://wadhwaniai.org/about/
          - text: "Blog"
            icon: pen-fill
            href: https://wadhwaniai.org/blog/
          
    right:
      - icon: github
        href: "https://github.com/WadhwaniAI"
      - icon: twitter
        href: https://twitter.com/WadhwaniAI
        aria-label: wadhwaniai.org Twitter


metadata-files: [nbdev.yml,sidebar.yml]