# Models
> THE obsession!

## Leaderboards
[ChatBot Arena](https://lmsys.org/blog/2023-05-10-leaderboard/). Elo rating for models (public and private)

## Open Zoo
Models with Permissive Licenses



> **Open LLaMA  ** \
models | paper | dataset  | [code](https://github.com/openlm-research/open_llama) | blog |\
An Open Source reproduction of LLaMA for permissive commerical uses.


> **GPT-Neo-X  ** \
[models](https://huggingface.co/docs/transformers/model_doc/gpt_neox) | [paper](https://arxiv.org/abs/2304.01373) | [dataset](https://pile.eleuther.ai/)  | [code](https://github.com/EleutherAI/gpt-neox) | blog |\
Many in this small family at [Pythia](https://github.com/EleutherAI/pythia). Based on The Pile datset.

> **GPT4All, GPT4ALL-LoRA  ** \
[models](https://huggingface.co/nomic-ai) | [paper](https://static.nomic.ai/gpt4all/2023_GPT4All-J_Technical_Report_2.pdf) | [dataset](https://huggingface.co/datasets/nomic-ai/gpt4all-j-prompt-generations) | [Code](https://github.com/nomic-ai/gpt4all) | [Blog](https://gpt4all.io/index.html) | \

> **Open Assistant  ** \
[models](https://huggingface.co/OpenAssistant) | [paper](https://arxiv.org/abs/2304.07327) | [dataset](https://huggingface.co/datasets/OpenAssistant/oasst1)| Code | Blog | \

> **Dolly 2  ** \
[models](https://huggingface.co/databricks/dolly-v2-12b) | paper | dataset| [Code](https://github.com/databrickslabs/dolly#getting-started-with-response-generation) | [Blog](https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm) | \
Based on GPT-Neo-X.

> **BLOOM  ** \
[models](https://huggingface.co/bigscience/bloom) | paper | dataset| Code | [Blog](https://bigscience.huggingface.co/blog/bloom) | \

> **Cerebras  ** \
[models](https://huggingface.co/cerebras/Cerebras-GPT-13B) | [paper](https://arxiv.org/abs/2304.03208) | dataset| Code | [Blog](https://www.cerebras.net/blog/cerebras-gpt-a-family-of-open-compute-efficient-large-language-models/) | \



## Semi-Open Zoo
Many in this category are, for most part, are derivates of LLaMA. Since LLaMA model weights were never released officially, the following only publish the weight deltas. Thefore, overall model is not permissive for commerical usages.

> **Falcon  ** \
[models](https://huggingface.co/tiiuae/falcon-40b-instruct) | paper| dataset| Code | [Blog](https://falconllm.tii.ae/) | \
Not based on LLaMA. Can use for commerical purposes provided you are [not minting money](https://huggingface.co/tiiuae/falcon-7b-instruct/blob/main/LICENSE.txt) :)


> **Guanaco  ** \
models | paper| dataset| Code | [Blog](https://the-decoder.com/guanaco-is-a-chatgpt-competitor-trained-on-a-single-gpu-in-one-day/) | \
Fine-tune LLaMA on a single GPU via QLoRA.


> **Gorilla  ** \
models | [paper](https://arxiv.org/abs/2305.15334) | dataset| [Code](https://github.com/ShishirPatil/gorilla) | [Blog](https://gorilla.cs.berkeley.edu/) | \
Beats GPT-4 on writing API calls.


> **Goat  ** \
[models]() | [paper](https://arxiv.org/abs/2305.14201) | dataset| [Code](https://github.com/liutiedong/goat) | Blog | \
Beats GPT-4 on Arithmetic tasks. Based on Alpaca-LoRA.


> **StableVicuna  ** \
[models](https://huggingface.co/CarperAI/stable-vicuna-13b-delta) | paper | dataset| [Code](https://github.com/Stability-AI/StableLM) | Blog | \


> **Vicuna  ** \
models | paper | dataset| [Code](https://github.com/lm-sys/FastChat) | [Blog](https://lmsys.org/blog/2023-03-30-vicuna/) | \

> **Kaola  ** \
models | paper | dataset| Code | [Blog](https://bair.berkeley.edu/blog/2023/04/03/koala/) | \
Introduces [EasyLM](https://github.com/young-geng/EasyLM) for code structuring and training in JAX.


> **Alpaca  ** \
models | [Paper](https://arxiv.org/abs/2302.13971v1) | [dataset](https://github.com/tatsu-lab/stanford_alpaca#data-release)| [code](https://github.com/tatsu-lab/stanford_alpaca) | [Blog](https://crfm.stanford.edu/2023/03/13/alpaca.html) | \
[Alpaca-LoRA](https://github.com/tloen/alpaca-lora) can run Raspberry Pi


> **LLaMA  ** \
[models](https://huggingface.co/docs/transformers/main/en/model_doc/llama) | [Paper](https://arxiv.org/abs/2302.13971v1) | dataset| Blog | \