# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm-wiki',
                'doc_host': 'https://WadhwaniAI.github.io',
                'git_url': 'https://github.com/WadhwaniAI/llm-wiki',
                'lib_path': 'llm_wiki'},
  'syms': {'llm_wiki.core': {'llm_wiki.core.foo': ('core.html#foo', 'llm_wiki/core.py')}}}
