# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llm-wiki',
                'doc_host': 'https://wadhwaniai.github.io',
                'git_url': 'https://github.com/wadhwaniai/llm-wiki',
                'lib_path': 'llm_wiki'},
  'syms': {}}
